### ISSUE TITLE
Add hidden SSID support

### ISSUE THREAD

**Issue by StefanScherer** [hypriot/device-init#24]
Linking issue hypriot/flash#74 from @mrgnou:

Actually, the generated wifi configuration doesn't provide hidden ssid support.
It would be nice to manage hidden wifi networks by adding an optional param scan-ssid to device-init.yaml such as:

``` yaml
hostname: black-pearl
wifi:
  interfaces:
    wlan0:
      ssid: "MyNetwork"
      scan-ssid: 1
      password: "secret_password"
```

This way, generated wlan0 file would look like

allow-hotplug wlan0

```
auto wlan0
iface wlan0 inet dhcp
  wpa-ssid MyNetwork
  wpa-scan-ssid 1
  wpa-psk generated_psk
```

**Comment by Govinda-Fichtner** [comment]
It looks like the configuration is still missing one line:

```
auto wlan0
iface wlan0 inet dhcp
  wpa-ssid MyNetwork
  wpa-ap-scan 1
  wpa-scan-ssid 1
  wpa-psk generated_psk
```

At least according to:

http://unix.stackexchange.com/questions/48431/connect-to-hidden-wifi-ap-with-wpa-supplicant

**Comment by StefanScherer** [comment]
What about adding the `wpa-ap-scan` like this? Is `wpa-psk` = `password` in yml?

```yml
wifi:
  interfaces:
    wlan0:
      ssid: "MyNetwork"
      scan-ssid: 1
      ap-scan: 1
      password: "secret_password"
```

**Comment by Govinda-Fichtner** [comment]
After some discussion Stefan and I thought it might be best if we rename the existing config settings for Wifi to the corresponding wpa config settings and just pass through all settings starting with "wpa-":

```
wifi:
  interfaces:
    wlan0:
      wpa-ap-scan: 1
      wpa-scan-ssid: 1
      wpa-ssid: "MyNetwork"
      wpa-proto: RSN
      wpa-pairwise: CCMP
      wpa-key-mgmt WPA-PSK
      wpa-psk "secret_password"
```
This way it is easy to lookup all the wpa-supplicant options and use the as needed.
