### ISSUE TITLE
Allow wifi connection to include optional identity

### ISSUE THREAD

**Issue by inodes** [hypriot/device-init#32]
Would like to provide an identity when connecting to 802.1X network which requires authentication using a username.
Could be achieved possibly using wpa_supplicant - 

```
hostname: black-pearl
wifi:
  interfaces:
    wlan0:
      ssid: "MyNetwork"
      scan-ssid: 1
      identity: "username"
      password: "secret_password"
```
