### ISSUE TITLE
Insert SSH pub keys

### ISSUE THREAD

**Issue by StefanScherer** [hypriot/device-init#7]
It would be super convenient for the `flash` script that it can add SSH pub keys while flashing that are inserted in the user's ~/.ssh/authorized_keys file.

Only a rough idea how that could look like in the device-init.yml file:

``` yaml
ssh:
  authorized_keys:
    root:
      - "sha-rsa AAA...NN"
    pirate:
      - "sha-rsa AAA...NN"
```
